services:
  app:
    build: .
    ports:
      - "8080:4000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development

  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
